import type { Metadata } from 'next';

import { Inter, Londrina_Solid, Island_Moments } from 'next/font/google';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
  weight: ['400', '900'],
});

const londrina_solid = Londrina_Solid({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-londrina-solid',
  weight: '400',
});
const island_moments = Island_Moments({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-island-moments',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${londrina_solid.variable} ${island_moments.variable} antialiased bg-background`}
      >
        {children}
      </body>
    </html>
  );
}
